services:
  app:
    image: node:20
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci --no-audit --no-fund || npm install --no-audit --no-fund && npm run dev:server"
    restart: unless-stopped